name: Build README

on:
  push:
    workflow_dispatch:
      schedule:
      - cron: '* * * * *'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '1.19'
    - run: go run cmd/main.go