name: Build README

on:
  schedule:
  - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '1.21'
    - run: go run cmd/main.go
      env:
        GITHUB_GRAPHQL_TOKEN: ${{ secrets.GRAPHQL_TOKEN }}
    - name: Commit README
      run: |
        git config --global user.name 'beep boop robot'
        git config --global user.email 'alexanderjophus@users.noreply.github.com'
        # if git diff then add and commit
        if [[ `git status --porcelain` ]]; then
          git add .
          git commit -m "Update README"
          git push
        fi